export const personnel1desc1: string = "Ibrahim Bin Jibreen has extensive experience managing all aspects of the design and construction process and provides overall leadership and direction to ensure the Construction Authority achieves its vision, mission, goals, and objectives."
export const personnel1desc2: string = "Mr. Jibreen organizes and manages Construction Authority staff and contractors to provide effective and efficient transportation. planning, and construction Approves and adopts Construction Authority’s policies, and procedures; and maintains accountability for the performance of the entire company."

export const personnel2desc1: string = "Emerson  L.  Tolentino, 53 years of age has 35 years of experience in the Kingdom of Saudi Arabia and currently serves as a MEP Project Director.  He has professional experience in project management and currently serves as Project Director of Ibrahim Bin Jibreen Company."
export const personnel2desc2: string = "He is responsible for providing business decisions and execution for the company. He controls the operation of the company’s project and is responsible for the overall performance and developed system addresses related to engineering construction and company policies. He is the key bridge of communication between the client and the company service."

export const personnel3desc1: string = "Mr. Hani, has 10 years plus experience as Finance Manager. He oversees the financial management and reporting activities of the company and is responsible for budget planning as well as supporting the executive management team in offering insights and financial advice that will allow them to make the best business decisions for the company."

export const personnel4desc1: string = "Mr. Waleed has 10 years plus experience as a Human Resource Manager. He was involved with recruitment, training, career development, compensation and benefits, employee relations, industrial relations, employment law, compliance, disciplinary and grievance issues, redundancies, etc. The job involves keeping up to date with areas  such as employment law, which change often."

export const personnel5desc1: string = "Mr. Abdelhadi has 12 years of experience in the procurement. He manages the purchasing of products and services for a company.  He creates a buying strategy that takes into account the company budget and necessary supplies and then they find matching vendors. Their day includes meetings with superiors, like the Chief Financial Officer (CFO) or the Chief Operating Officer (COO). Generally, supervisors task Procurement Managers with finding suppliers that meet demands at the right price."

export const personnel6desc1: string = "Sisay, 38 years of age, has 12 years of experience in the kingdom of Saudi Arabia and currently serves as a Project Coordinator. He has professional experience in human resource management and currently responsible for overseeing a team employees who help plan and carry out events, organized negotiation and communication for clients and company."
